# Use the Node.js image
FROM node:16

WORKDIR /app

# Copy package files and install dependencies
COPY client/package.json client/package-lock.json ./
RUN npm install

# Copy the client code
COPY client/ ./

EXPOSE 3000

CMD ["npm", "run", "dev"]
