version: "3"
services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app

  server:
    build:
      context: .
      dockerfile: server/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
