version: '3.8'
services:
  client:
    build:
      context: .
      target: runner
      dockerfile: client/Dockerfile.dev
    volumes:
      - ./client:/app
    command: npm start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

  server:
    build:
      context: .
      dockerfile: server/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
