import styled from "styled-components";

export const SignupSectionContainer = styled.section`
    display: flex;
    justify-content: center;
    width: 100%;
    background-color: #316aff;
    background-image: 
        radial-gradient(at 47% 33%, hsl(162.42, 0%, 100%) 0, transparent 59%), 
        radial-gradient(at 82% 65%, hsl(223.40, 100%, 60%) 0, transparent 55%);
`

export const SignupSectionWrapper = styled.div`
    display: flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    max-width: 1200px;
    min-height: 90vh;
    padding: 20px 0;
    
    
    @media (max-width: 1150px) {
        padding: 20px 20px;
    }
    @media (max-width: 700px) {
        align-items: start;
        padding: 50px 10px 0 15px;
    }
`

export const ImageContainer = styled.div`
    flex: 1;
    display: flex;
    align-items: flex-start;
    width: 100%;
    flex-direction: column;
    text-align: left;
    overflow: hidden;
    padding: 30px 10px;
    img{
        transform: scale(1.2);
    }
    h2{
        text-transform: uppercase;
    }
    @media (max-width: 700px) {
        align-items: center;
        img{
            transform: unset;
            height: 250px;
        }
    }
`

export const FormContainer = styled.div`
    display: flex;
    width: 100%;
    /* height: 100%; */
    max-width: 500px;
    /* min-height: 500px; */
    padding: 20px 0;
    flex-direction: column;
    gap: 10px;
    transition: 300ms all ease-in-out; 

    backdrop-filter: blur(9px) saturate(155%);
    -webkit-backdrop-filter: blur(9px) saturate(155%);
    background-color: rgba(255, 255, 255, 0.98);
    border-radius: 30px;
    border: 1px solid rgba(209, 213, 219, 0.3);
`

export const LoginText = styled.p`
    text-align: center;
    font-weight: 600;
    span{
        color: #316aff;
        cursor: pointer;
    }
`

export const BusinessFormContainer = styled.div`
    display: flex;
`

/* Background styles 
body {
    background-color: #316aff;
    background-image: 
        radial-gradient(at 47% 33%, hsl(162.42, 0%, 100%) 0, transparent 59%), 
        radial-gradient(at 82% 65%, hsl(223.40, 100%, 60%) 0, transparent 55%);
}

.card {
    backdrop-filter: blur(9px) saturate(155%);
    -webkit-backdrop-filter: blur(9px) saturate(155%);
    background-color: rgba(255, 255, 255, 0.98);
    border-radius: 12px;
    border: 1px solid rgba(209, 213, 219, 0.3);
}

/* Generated by https://generator.ui.glass/ */