# Use the Node.js image
FROM node:16

WORKDIR /app

# Copy package files and install dependencies
COPY server/package.json server/package-lock.json ./
RUN npm install

# Copy the server code
COPY server/ ./

EXPOSE 8080

CMD ["npx", "nodemon", "server.js"]
